config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :contributions
  resources :comments

  resources :contributions, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]

    post :upvote, on: :member
    post :upvotecomment, on: :member
    post :destroy, on: :member

  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'contributions#index'
  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/comments/:id' => 'comments#createWithParent'

  #api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:show, :create, :update, :destroy]
      resources :contributions, only: [:index, :show, :create, :update, :destroy] do # afegit aixo per a que no renderitzi els altres endpoints
        resources :comments, only: [:index, :show, :create, :update, :destroy] 
      end
      
      get 'users/:id/comments', to: 'users#threads'

      post 'contributions/:id/vote' => 'contributions#vote'
      post 'contributions/:id/unvote' => 'contributions#unvote'
      post 'contributions/:contribution_id/comments/:id/vote' => 'comments#vote'
      post 'contributions/:contribution_id/comments/:id/unvote' => 'comments#unvote'

      post 'contributions/:contribution_id/comments/:id/reply' => 'comments#replyComment'

      post 'login' => 'sessions#getSession'

    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :contributions, dependent: :destroy
  has_many :comments
  validates :name, presence: true
  validates :api_key, uniqueness: true
  has_many :votes
  has_many :votecomments
  before_create :generate_api_key
  
  # poder alguns camps que es guarden no ens faran falta o haurem d'afegir mes
  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(name: auth_hash.info.nickname).first_or_create
    user.update(
      provider: auth_hash.provider, 
      uid: auth_hash.uid,
      token: auth_hash.credentials.token,
      secret: auth_hash.credentials.secret
    )
    user
  end

  def self.find_by_auth_params(provider, uid, nickname, token, secret)
    user = where(name: nickname).first_or_create
    user.update(
      provider: provider, 
      uid: uid,
      token: token,
      secret: secret
    )
    user
  end

  def owns_contribution?(contribution)
    self == contribution.user
  end

  def owns_comment?(comment)
    self == comment.user
  end

  def upvotecomment(comment)
    votecomments.create(upvotecom: 1, comment: comment)
  end
  
  def upvotedcomment?(comment)
     votecomments.exists?(upvotecom: 1, comment: comment)
  end

  def hasvotedcomment?(comment)
    votecomments.exists?(comment: comment)
  end

  def remove_votecomment(comment)
    votecomments.find_by(comment: comment).destroy
  end
  
  def upvote(contribution)
    votes.create(upvote: 1, contribution: contribution)
  end  

  def upvoted?(contribution)
    votes.exists?(upvote: 1, contribution: contribution)
  end

  def hasvoted?(contribution)
    votes.exists?(contribution: contribution)
  end
  
  def remove_vote(contribution)
    votes.find_by(contribution: contribution).destroy
  end
  
  def generate_api_key
    if self.api_key.length == 0
      self.api_key = SecureRandom.hex
    end
  end
  
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApiController
  before_action :current_user

  def create
    if params[:name] == nil or params[:name] == ""
      render json: {message: "A user should have a name."}, status: 400 and return
    end

    existant = User.find_by_name(params[:name])
    if existant != nil
      render json: { message: "This name already exists"}, status: 409 and return
    end

    @user = User.new
    @user.name = params[:name]
    @user.email = params[:email]
    @user.about = params[:about]

    if @user.save
      render json: @user, serializer: UserSerializer, status: 201 and return
    else
      render json: @user.errors, status: 500 and return
    end
  end
  
  def show
    if !@current_user
      send_unauthorized
    else
      @user = User.find_by_id(params[:id])
      if @user.nil?
        render json: { message: "User not found"}, status: 404 and return
      else
        if @user.id == @current_user.id
          render json: @user, serializer: UserSerializer, status: 200 and return
        else
          render json: @user, serializer: UserSimpleSerializer, root: 'user', status: 200 and return
        end
      end
    end
  end

  def update
    if !@current_user
      send_unauthorized
    else
      @user = User.find_by_id(params[:id])
      if @user.nil?
        render json: { message: "This user doesn't exist"}, status: 404 and return
      end
      
      if @user.id != @current_user.id
        render json: { message: "Not authorized to update this user"}, status: 403 and return
      end
      
      if params[:email] != nil
        @user.email = params[:email]
      end
      if params[:about] != nil
        @user.about = params[:about]
      end
      
      if @user.changed?
        if @user.save
          render json: @user, serializer: UserSerializer, status: 200 and return
        else
          render json: @user.errors, status: 500 and return
        end
      else
        render json: @user, serializer: UserSerializer, status: 200 and return
      end
    end
  end
  
  def destroy
    if !@current_user
      send_unauthorized
    else
      @user = User.find_by_id(params[:id])
      if @user.nil?
        render json: { message: "This user doesn't exist"}, status: 404 and return
      end
      
      if @user == @current_user
        @user.contributions.destroy_all
        @user.comments.destroy_all
        @user.destroy
        render json: { message: "All the data from this user has been deleted."}, status: 200 and return
      else
        render json: {message: "You don't have permissions to delete this user."}, status: 403 and return
      end
    end
  end
  
  def threads
    if !@current_user
      send_unauthorized
    else
      @user = User.find_by_id(params[:id])
      if @user.nil?
        render json: { message: "This user doesn't exist"}, status: 404 and return
      end
      
      if @user == @current_user
        @comments = @user.comments
        render json: @comments, each_serializer: CommentSerializer, root: 'comments', status: 200 and return
      else
        render json: {message: "You don't have permissions to access this user."}, status: 403 and return
      end
    end
  end
  
  def send_unauthorized
    render json: { message: "Invalid Token or missing token" }, status: 401 and return
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :prevent_unauthorized_user_access, except: [:show, :index]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    if params[:type] == 'threads'
      @comments = Comment.where(user: :current_user).all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if logged_in? and current_user.id==@user.id
      
    else
      redirect_to root_path, notice: "Not authorized to edit this user"
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :about)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_area :about, id: :user_about %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>Editing User</h2>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', contributions_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Users</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Created</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= time_ago_in_words(user.created_at) %> ago</td>
        <td><%= user.about %></td>
        <td><%= link_to 'Show', user %></td>
        <% if logged_in? and current_user.id==user.id %>
          <td><%= link_to 'Edit', edit_user_path(user)%></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h2>New User</h2>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Created:</strong>
  <%= time_ago_in_words(@user.created_at) %> ago
</p>

<% if logged_in? and current_user.id==@user.id%>
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  <p>
    <strong>Api-Key:</strong>
    <%= @user.api_key %>
  </p>
<% end %>

<p>
  <strong>About:</strong>
  <%= @user.about %>
</p>

<% if logged_in? and current_user.id==@user.id %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
<% end %>
<%= link_to 'Back', contributions_path %>