config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :contributions
  resources :comments

  resources :contributions, except: :index do
    resources :comments, only: [:create, :edit, :update, :destroy]

    post :upvote, on: :member
    post :upvotecomment, on: :member
    post :destroy, on: :member

  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'contributions#index'
  
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/comments/:id' => 'comments#createWithParent'

  #api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:show, :create, :update, :destroy]
      resources :contributions, only: [:index, :show, :create, :update, :destroy] do # afegit aixo per a que no renderitzi els altres endpoints
        resources :comments, only: [:index, :show, :create, :update, :destroy] 
      end
      
      get 'users/:id/comments', to: 'users#threads'

      post 'contributions/:id/vote' => 'contributions#vote'
      post 'contributions/:id/unvote' => 'contributions#unvote'
      post 'contributions/:contribution_id/comments/:id/vote' => 'comments#vote'
      post 'contributions/:contribution_id/comments/:id/unvote' => 'comments#unvote'

      post 'contributions/:contribution_id/comments/:id/reply' => 'comments#replyComment'

      post 'login' => 'sessions#getSession'

    end
  end
  
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :user
  #default_scope -> { order(created_at: :desc) }
  scope :hottest, -> { order(points: :desc) }

  validates :url, :format => URI::regexp(%w(http https)) , :allow_blank => true
  has_many :comments, dependent: :destroy #, :class_name => 'Contribution'
  has_many :votes, dependent: :destroy
  
  def upvotes
    votes.sum(:upvote)
  end
  def upComments()
    self.numComments += 1
  end 

  def downComments(count)
    self.numComments -= count
  end

  def calc_hot_score
    points = upvotes
    time_ago_in_hours = ((Time.now - created_at) / 3600).round
    score = hot_score_m(points)
    update_attributes(points: points, hot_score: score)
  end
  
  private 
  def hot_score_m(points)
    points
  end
  
end

app/controllers/api/v1/contributions_controller.rb
class Api::V1::ContributionsController <  Api::V1::ApiController
  protect_from_forgery with: :null_session
  before_action :current_user

  #FIXME: Aixo es lo que fa resources
  # GET 	      /photos 	-->         photos#index 	display a list of all photos --> s'implementa
  # GET 	      /photos/new 	-->     photos#new 	return an HTML form for creating a new photo --> NO
  # POST 	      /photos 	-->         photos#create 	create a new photo --> s'implementa
  # GET       	/photos/:id 	-->     photos#show 	display a specific photo --> s'implementa
  # GET       	/photos/:id/edit 	--> photos#edit 	return an HTML form for editing a photo --> NO
  # PATCH/PUT   /photos/:id 	-->     photos#update 	update a specific photo --> s'implementa
  # DELETE     	/photos/:id 	-->     photos#destroy 	delete a specific photo --> s'implementa

  def index
    if !@current_user
      send_unauthorized
    else
      if params[:type] == "ask"
        @contributions = Contribution.where(url: nil).order(points: :desc).all
      elsif params[:type] == "new"
        @contributions = Contribution.order(id: :desc).all
      elsif params[:type] == nil
        @contributions = Contribution.where(text: nil).hottest
      else
        render json: { message: "Bad Request" }, status: 400 and return
      end
      
      render json: @contributions, each_serializer: ContributionSimpleSerializer, status: 200 and return
      
    end
  end


  def create
    if !@current_user
      send_unauthorized 
    else

      if params[:title] == nil or params[:title] == ''
        render json: {message: "The title field is required"}, status: 400 and return
      end
      
      @contribution = Contribution.new
      @contribution.title = params[:title]
      @contribution.user_id = @current_user.id
      @contribution.numComments = 0
      @contribution.points = 0

      if params[:url] != nil and params[:url] != ''
        if params[:text] != nil and params[:text] != ''
          render json: {message: "Unable to create, you must choose between type url or type ask"}, status: 400 and return
        end
        existant = Contribution.find_by(url: params[:url])
        if existant != nil
          render json: {message: "This contribution already exists. Id of this contribution:" + existant.id.to_s}, status: 409 and return
        else
          @contribution.url = params[:url]
        end
      elsif params[:text] != nil and params[:text] != ''
        if params[:url] != nil and params[:url] != ''
          render json: {message: "Unable to create, you must choose between type url or type ask"}, status: 400 and return
        end
        @contribution.text = params[:text]
      else
        render json: {message: "Cannot create a Contribution without text nor url"}, status: 400 and return
      end
      
      if @contribution.save
        render json: @contribution, serializer: ContributionSimpleSerializer, status: 201 and return
      else
        render json: @contribution.errors, status: 500 and return
      end
    end
  end
  

  def show
    if !@current_user
      send_unauthorized
    else
      @contribution = Contribution.find_by_id(params[:id])
      if @contribution.nil?
        render json: { message: "Contribution not found"}, status: 404 and return 
      else
        render json: @contribution, serializer: ContributionSerializer, status: 200 and return
      end
    end
  end

  def vote
    if !@current_user
      send_unauthorized
    else
      @contribution = Contribution.find_by_id(params[:id])
      if @contribution.nil?
        render json: { message: "This contribution doesn't exist"}, status: 404 and return 
      else
        if current_user.upvoted?(@contribution)
          render json: { message: "You have already voted this contribution."}, status: 409 and return
        else
          current_user.upvote(@contribution)
          @contribution.calc_hot_score
          render json: { message: "You have voted this contribution."}, status: 200 and return
        end
      end
    end
  end

  def unvote
    if !@current_user
      send_unauthorized
    else
      @contribution = Contribution.find_by_id(params[:id])
      if @contribution.nil?
        render json: { message: "This contribution doesn't exist"}, status: 404 and return 
      else
        if current_user.upvoted?(@contribution)
          current_user.remove_vote(@contribution)
          @contribution.calc_hot_score
          render json: { message: "You have removed your vote from this contribution."}, status: 200 and return
        else
          render json: { message: "You can't unvote something you haven't voted."}, status: 409 and return
        end
      end
    end
  end
  

  def update
    if !@current_user
      send_unauthorized
    else
      @contribution = Contribution.find_by(id: params[:id])
      if @contribution == nil
        render json: { message: "This contribution doesn't exist"}, status: 404 and return
      end
      
      if !@current_user.owns_contribution?(@contribution)
        render json: { message: "Not authorized to update this contribution"}, status: 403 and return
      end

      if params[:title] != nil
        @contribution.title = params[:title]
      end

      if params[:url] != nil and params[:url] != ''
        if params[:text] != nil and params[:text] != ''
          render json: { message: "Unable to update, you must choose between type url or type ask"}, status: 400 and return
        end
        @contribution.url = params[:url]
        @contribution.text = nil
      elsif params[:text] != nil and params[:text] != ''
        if params[:url] != nil and params[:url] != ''
          render json: { message: "Unable to update, you must choose between type url or type ask"}, status: 400 and return
        end
        @contribution.text = params[:text]
        @contribution.url = nil
      end

      if @contribution.changed?
        if @contribution.save
          render json: @contribution, serializer: ContributionSimpleSerializer, status: 200 and return 
        else
          render json: @contribution.errors, status: 500 and return 
        end
      else
        render json: @contribution, serializer: ContributionSimpleSerializer, status: 200 and return
      end
    end
  end

  def destroy
    if !@current_user
      send_unauthorized 
    else
      @contribution = Contribution.find_by(id: params[:id])
      if @contribution == nil
        render json: { message: "This contribution doesn't exist"}, status: 404 and return
      end
      if @current_user.owns_contribution?(@contribution)
        @contribution.comments.destroy
        @contribution.votes.destroy
        @contribution.destroy
        render json: { message: "Contribution deleted successfully"}, status: 200 and return
      else
        render json: { message: "Not authorized to delete this contribution"}, status: 403 and return
      end
    end
  end

  def send_unauthorized
    render json: { message: "Invalid Token or missing token" }, status: 401 and return
  end

end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]
  before_action :prevent_unauthorized_user_access, except: [:show, :index]
  # GET /contributions
  # GET /contributions.json
  def index
    if params[:type] == 'new'
      @contributions = Contribution.order(id: :desc).all
    elsif params[:type] == 'ask'
      @contributions = Contribution.where(url: nil).order(points: :desc).all
    # elsif params[:type] == 'threads'
    #   @contributions = Contribution.where(url: nil).order(id: :asc).all
    else
      @contributions = Contribution.where(text: nil).hottest;
    end
  end


  # GET /contributions/1
  # GET /contributions/1.json
  def show
    
  end

  # GET /contributions/new
  def new
    @contribution = Contribution.new
  end

  # GET /contributions/1/edit
  def edit
    contribution = Contribution.find_by(id: params[:id])

    if current_user.owns_contribution?(contribution)
      @contribution = contribution
    else
      redirect_to root_path, notice: "Not authorized to edit this link"
    end

  end

  # POST /contributions
  # POST /contributions.json
  def create
    # @contribution = Contribution.new(contribution_params)
    @contribution = current_user.contributions.new(contribution_params)
    @contribution.numComments = 0
    @contribution.points = 0
    if @contribution.url == '' and @contribution.text != '' #es vacio o con espacios trolls
      @contribution.url = nil
      respond_to do |format|
        if @contribution.save
          format.html { redirect_to "/contributions?type=ask"}
          format.json { render :show, status: :created, location: @contribution }
        else
          format.html { render :new }
          format.json { render json: @contribution.errors, status: :unprocessable_entity }
        end
      end
    elsif @contribution.url != '' and @contribution.text == '' #nil = null
      @contribution.text = nil
      existant = Contribution.find_by(url: @contribution.url)
      
      if existant
        @contribution = existant
        idTo = existant.id.to_s
        respond_to do |format|
          format.html { redirect_to "/contributions/"+idTo, notice: "This contribution already exists."}
          format.json { render :show, status: :created, location: @contribution }
        end
      else
        respond_to do |format|
          if @contribution.save
            format.html { redirect_to "/contributions"}
            format.json { render :show, status: :created, location: @contribution }
          else
            format.html { render :new }
            format.json { render json: @contribution.errors, status: :unprocessable_entity }
          end
        end
      end

    elsif @contribution.url != '' and @contribution.text != ''
      respond_to do |format|
        format.html { redirect_to "/contributions/new", notice: "Unable to create, you must choose between type url or type ask" }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contributions/1
  # PATCH/PUT /contributions/1.json
  def update
    respond_to do |format|
      if @contribution.update(contribution_params)
        format.html { redirect_to contributions_url}
        format.json { render :show, status: :ok, location: @contribution }
      else
        format.html { render :edit }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributions/1
  # DELETE /contributions/1.json
  def destroy

    @contribution = Contribution.find_by(id: params[:id])
    if current_user.owns_contribution?(@contribution)
      @contribution.comments.destroy
      @contribution.votes.destroy
      @contribution.destroy
      redirect_back(fallback_location: root_path, notice: "Contribution successful deleted")

    else
      redirect_back(fallback_location: root_path, notice: "Not authorized to edit this contribution")
    end
  end
  
  def upvotecomment
    @comment = Comment.find(params[:id])
    if current_user.upvotedcomment?(@comment)
      current_user.remove_votecomment(@comment)
    else
      current_user.upvotecomment(@comment)
    end
    redirect_back(fallback_location: root_path)
  end

  def upvote
    contribution = Contribution.find_by(id: params[:id])

    if current_user.upvoted?(contribution)
      current_user.remove_vote(contribution)
    else
      current_user.upvote(contribution)
    end
    contribution.calc_hot_score
    redirect_back(fallback_location: root_path)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contribution
      @contribution = Contribution.find(params[:id])
      @comments = @contribution.comments
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contribution_params
      params.require(:contribution).permit(:title, :url, :text) #TODO: perquè comment_id?
    end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/_form.html.erb
<p id="notice"><%= notice %></p>
<%= form_with(model: contribution, local: true) do |form| %>
  <% if contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

      <ul>
      <% contribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, :title,  style: 'font-family: Verdana, Geneva, sans-serif; font-size: 10pt; color: #828282;   display: inline-block;' %>
    <%= form.text_field :title, required: true, id: :contribution_title, size: '50' %>
  </div>
  <div class="field">
    <%= form.label :url, :url , style: 'font-family: Verdana, Geneva, sans-serif; font-size: 10pt; color: #828282;   display: inline-block;' %>
    <%= form.text_field :url, id: :contribution_url, size: '50', style: 'margin-left: 1%;'%>
  </div>
  <b style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt; color: #828282; margin-left: 3%">or</b>
  <div class="field">
    <%= form.label :text, :ask, style: 'font-family: Verdana, Geneva, sans-serif; font-size: 10pt; color: #828282;   display: inline-block; position: absolute; margin-top:2.5%' %>
    <%= form.text_area :text, id: :contribution_text, rows: '4', cols: '70', style: 'margin-left:3%;' %>
  </div>
  <div class="actions">
    <%= form.submit "submit", style: 'font-family: monospace; font-size: 10pt; margin-left: 3%'  %>
  </div>
  </br>
  <p style="font-family: Verdana, Geneva, sans-serif; font-size: 10pt; color: #828282; margin-left:3%">Leave url blank to submit a question for discussion. If there is no url, the text (if any) will appear at the top of the thread.</p>
    
<% end %>

app/views/contributions/edit.html.erb
<h2>Editing Contribution</h2>

<%= render 'form', contribution: @contribution %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Contributions</h2>

<table border="0" cellpadding="0" cellspacing="0" class="itemlist">

<% @contributions.each_with_index do |contribution, index| %>
  <tr class='athing' id='myIdTODO'>

  <td align="right" valign="top" class="title">
    <span class="rank"><%= index %>.</span>
  </td>

  <td valign="top" class="votelinks">
    <center>
      <div>
        <% if logged_in? && current_user.hasvoted?(contribution) %>
          <%= link_to "▼", upvote_contribution_path(contribution), method: :post, class: "votearrow" %>
        <% else %>
          <div>
            <%= link_to "▲", upvote_contribution_path(contribution), method: :post, class: "votearrow" %>
          </div>
        <% end %>
      <%= contribution.upvotes %>
    </center>
  </td>
  <td class="title">
    <% if !contribution.url.blank? %>
      <span>Type url</span> |
      <a href="<%= contribution.url %>" class="storylink"><%= contribution.title %></a>

      <span class="sitebit comhead"> (<a href="<%= contribution.url %>"><span class="sitestr"><%= contribution.url %></span>
        </a>)</span>

    <% end %>
    <% if contribution.url.blank? %>
    <span>Type text</span> |
    <a class="storylink"><%= contribution.title %></a>
      <span>Text: <%= contribution.text %></span>
    <% end %>
    <span>by @<%= link_to contribution.user.name, contribution.user %></span>
    <span><%= time_ago_in_words(contribution.created_at) %> ago</span>
            |
     <%if contribution.numComments == 0%>
        <a href="/contributions/<%=contribution.id%>">Discuss</a>
    <%elsif contribution.numComments == 1%>
        <a href="/contributions/<%=contribution.id%>"><%=contribution.numComments%> comment</a>
    <%else%>
        <a href="/contributions/<%=contribution.id%>"><%=contribution.numComments%> comments</a>
    <%end%>
  </td>

  <td><%= link_to 'Show', contribution %></td>

  <% if logged_in? && current_user.owns_contribution?(contribution) %>
    <td><%= link_to 'Edit', edit_contribution_path(contribution) %></td>
    <td><%= link_to 'Destroy', contribution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
<% end %>

  </tr>
</table>


<table>
  
</table>

<br>

<%-# <%= link_to 'New Contribution', new_contribution_path-%>

app/views/contributions/new.html.erb
<h2>New Contribution</h2>

<%= render 'form', contribution: @contribution %>

<%= link_to 'Back', contributions_path %>

app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>

<section>
  <header>
    <h4>
      <strong>Title:</strong>
      <%= @contribution.title %>
    </h4>

    <% if @contribution.text? %>
      <p>
        <strong>Text:</strong>
        <%= @contribution.text %>
      </p>
    <% end %>
    <% if @contribution.url? %>
      <p>
        <strong>Url:</strong>
        <%= @contribution.url %>
      </p>
    <% end %>
    
  </header>
</section>

<% if logged_in? %>
    <div class="add-comment row">
      <div class="col-sm-6">
        <%= form_for :comment, url: contribution_comments_path(@contribution) do |f| %>
          <div class="form-group">
            <%= f.text_area :body, class: "form-control", placeholder: "The quick brown fox...", rows: 10, required: true %>
          </div>

          <div class="form-group">
            <%= f.button "add comment", class: "btn btn-success" %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

<div class="all-comments row">
    <div class="col-sm-12">
      <% if @contribution.comments.present? %>
        <h3>
          Comments
        </h3>
      <% end %>
      
      <% @contribution.comments.each do |reply| %>
        <div>
          <% if reply.parent == nil %>
            <p class="comment-owner">
              <% if logged_in? && current_user.upvotedcomment?(reply) %>
                <%= link_to "▼", upvotecomment_contribution_path(reply), method: :post, class: "votearrow" %>
              <% else %>
                <%= link_to "▲", upvotecomment_contribution_path(reply), method: :post, class: "votearrow" %>
              <% end %>
              <%= reply.upvotecomments %>
              <strong>
                @<%= link_to reply.user.name, reply.user%>
              </strong>

              <span class="comment-created small">
                <%= time_ago_in_words(reply.created_at) %> ago
              </span>
            </p>
            <p><%= reply.body %></p>
            <%= link_to "Reply", controller: "comments", action: "show", id: reply.id%>
            <% if logged_in? %>
              <% if current_user.owns_comment?(reply) %>
                <%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            <% end %>
            <%= render partial: "comments/comment", locals: { reply: reply } %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_contribution_path(@contribution) %> |
<%= link_to 'Back', contributions_path %>